# Generated by go2rpm 1.9.0
%bcond_without check
# pull in deps dynamically from the web
%global gomodulesmode GO111MODULE=on

# https://github.com/juanfont/headscale
%global goipath         github.com/juanfont/headscale
Version:                0.21.0
%gometa -f


%global common_description %{expand:
An open source, self-hosted implementation of the Tailscale control server.}

%global golicenses      LICENSE

Name:           headscale
Release:        1
Summary:        An open source, self-hosted implementation of the Tailscale control server

License:        BSD-3-Clause
URL:            %{gourl}
Source:         https://github.com/juanfont/headscale/archive/v%{version}/headscale-%{version}.tar.gz

BuildRequires:  git-core

%description %{common_description}


%gopkg


%prep
%goprep
%autopatch -p1

#%%generate_buildrequires
#%%go_generate_buildrequires


%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done


%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/


%if %{with check}
#%%check
#%%gocheck
%endif


%files
%license LICENSE
%doc docs/ README.md CHANGELOG.md
%{_bindir}/headscale
%exclude %{_bindir}/gh-action-integration-generator

%gopkgfiles


%changelog
* Wed Apr 19 2023 Jonathan Wright <jonathan@almalinux.org> - 0.21.0-1
- Initial package build
