# Generated by go2rpm 1.9.0
%bcond_without check
# pull in deps dynamically from the web
%global gomodulesmode GO111MODULE=on

# https://github.com/juanfont/headscale
%global goipath         github.com/juanfont/headscale
Version:                0.21.0
%gometa -f


%global common_description %{expand:
An open source, self-hosted implementation of the Tailscale control server.}

%global golicenses      LICENSE

Name:           headscale
Release:        1
Summary:        An open source, self-hosted implementation of the Tailscale control server

License:        BSD-3-Clause
URL:            %{gourl}
Source:         https://github.com/juanfont/headscale/archive/v%{version}/headscale-%{version}.tar.gz

BuildRequires:  git-core
%if 0%{?rhel}
BuildRequires:  wget
%endif

%description %{common_description}


%gopkg


%prep
%goprep
%autopatch -p1

# we don't need to build this
rm -rf cmd/gh-action-integration-generator

#%%generate_buildrequires
#%%go_generate_buildrequires


%build
%if 0%{?rhel}
    # need to look into this more
    %undefine _missing_build_ids_terminate_build
    mkdir %{_topdir}/go
    pushd %{_topdir}/go
    wget https://go.dev/dl/go1.19.8.linux-amd64.tar.gz
    tar -xf go1.19.8.linux-amd64.tar.gz
    popd
    export GOROOT=%{_topdir}/go/go
    export PATH="${GOROOT}/bin:${PATH}"
%endif

for cmd in cmd/* ; do
  %if 0%{?rhel}
    go build -v -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
  %else
    %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
  %endif
done


%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/


%if %{with check}
#%%check
#%%gocheck
%endif


%files
%license LICENSE
%doc docs/ README.md CHANGELOG.md
%{_bindir}/headscale

%gopkgfiles


%changelog
* Wed Apr 19 2023 Jonathan Wright <jonathan@almalinux.org> - 0.21.0-1
- Initial package build
